In [1]:
import tensorflow as tf
from tensorflow import keras
from keras.layers import Dense, Flatten, InputLayer, Conv2D, MaxPool2D
import pandas as pd
import numpy as np
import cv2
import os
import matplotlib.pyplot as plt

In [2]:
# Load the data

# Get current working directory
current_dir = os.getcwd()
os.makedirs(current_dir + '/data', exist_ok=True)
# Append data/mnist.npz to the previous path to get the full path
data_path = os.path.join(current_dir, "data/mnist.npz")
(x_train, y_train), _ = tf.keras.datasets.mnist.load_data(path=data_path)


In [3]:
y_train[:10]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4], dtype=uint8)

In [4]:
# Discard test set

        
# Normalize pixel values
x_train = x_train / 255.0

In [5]:
print(len(x_train), x_train.shape)

60000 (60000, 28, 28)


In [6]:
model = keras.Sequential([InputLayer(input_shape=(28, 28)),
                          Flatten(),
                          Dense(256, activation=tf.nn.relu),
                          Dense(10, activation=tf.nn.softmax)])

In [7]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 256)               200960    
_________________________________________________________________
dense_1 (Dense)              (None, 10)                2570      
Total params: 203,530
Trainable params: 203,530
Non-trainable params: 0
_________________________________________________________________


In [8]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['acc'])

In [9]:
model.fit(x_train, y_train, epochs=20)

Epoch 1/20
1875/1875 [==============================] - 12s 6ms/step - loss: 0.2240 - acc: 0.9349
Epoch 2/20
1875/1875 [==============================] - 11s 6ms/step - loss: 0.0913 - acc: 0.9727
Epoch 3/20
1875/1875 [==============================] - 11s 6ms/step - loss: 0.0603 - acc: 0.9816
Epoch 4/20
1875/1875 [==============================] - 11s 6ms/step - loss: 0.0441 - acc: 0.9860
Epoch 5/20
1875/1875 [==============================] - 12s 6ms/step - loss: 0.0339 - acc: 0.9897
Epoch 6/20
1875/1875 [==============================] - 12s 6ms/step - loss: 0.0256 - acc: 0.9917
Epoch 7/20
1875/1875 [==============================] - 11s 6ms/step - loss: 0.0184 - acc: 0.9944
Epoch 8/20
1875/1875 [==============================] - 12s 6ms/step - loss: 0.0174 - acc: 0.9944
Epoch 9/20
1875/1875 [==============================] - 12s 6ms/step - loss: 0.0138 - acc: 0.9955
Epoch 10/20
1875/1875 [==============================] - 12s 6ms/step - loss: 0.0107 - acc: 0.9965
Epoch 11/20
1875/18

In [10]:
model.evaluate(x_train, y_train)

1875/1875 [==============================] - 6s 3ms/step - loss: 0.0030 - acc: 0.9991


[0.0029861456714570522, 0.9991166591644287]

In [11]:
yhat = model.predict(x_train[:20, :, :])

In [12]:
np.argmax(yhat, axis=1)

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4, 3, 5, 3, 6, 1, 7, 2, 8, 6, 9],
      dtype=int64)

In [13]:
y_train[:20]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4, 3, 5, 3, 6, 1, 7, 2, 8, 6, 9],
      dtype=uint8)

In [14]:
model1 = keras.Sequential([InputLayer(input_shape=(28, 28, 1)),
                          Conv2D(64, 3, activation='relu'),
                          MaxPool2D(),
                          Conv2D(16, 3, activation='relu'),
                          MaxPool2D(),
                          Flatten(),
                          Dense(128, activation='relu'),
                          Dense(10, activation='softmax')])

model1.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 26, 26, 64)        640       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 13, 13, 64)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 11, 11, 16)        9232      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 5, 5, 16)          0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 400)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 128)               51328     
_________________________________________________________________
dense_3 (Dense)              (None, 10)               

In [15]:
model1.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['acc'])

In [16]:
x_train_1 = np.expand_dims(x_train, axis=-1)
print(len(x_train_1), x_train_1.shape)

60000 (60000, 28, 28, 1)


In [17]:
model1.fit(x_train_1, y_train, epochs=3)

Epoch 1/3
1875/1875 [==============================] - 138s 73ms/step - loss: 0.1554 - acc: 0.9520
Epoch 2/3
1875/1875 [==============================] - 137s 73ms/step - loss: 0.0508 - acc: 0.9841
Epoch 3/3
1875/1875 [==============================] - 129s 69ms/step - loss: 0.0359 - acc: 0.9886


In [19]:
model1.evaluate(x_train_1, y_train)

1875/1875 [==============================] - 2s 1ms/step - loss: 0.0256 - acc: 0.9918


[0.025607416406273842, 0.9918333292007446]