In [1]:
import pandas as pd
import numpy as np
import os

import tensorflow as tf
from tensorflow import keras

import matplotlib.pyplot as plt
%matplotlib inline

##### Functions

#### tf.data.Dataset.from_tensor_slices
https://www.tensorflow.org/api_docs/python/tf/data/Dataset#from_tensor_slices


#### x.window



In [2]:
print('-----------------------------------------window')
x = range(10)
x = tf.data.Dataset.from_tensor_slices(x)
x = x.window(3)
for el in x:
    print(list(el.as_numpy_iterator()))

print('-----------------------------------------winow - add shift argument')
x = range(10)
x = tf.data.Dataset.from_tensor_slices(x)
x = x.window(3, shift=1)
for el in x:
    print(list(el.as_numpy_iterator()))
    
print('-----------------------------------------batch--1')
x = range(10)
x = tf.data.Dataset.from_tensor_slices(x)
x = x.window(3, shift=1)
for el in x:
    print(list(el.batch(2).as_numpy_iterator()))
    
print('-----------------------------------------batch--2')
x = range(10)
x = tf.data.Dataset.from_tensor_slices(x)
for el in x.batch(3):
    print(el.numpy())


-----------------------------------------window
[0, 1, 2]
[3, 4, 5]
[6, 7, 8]
[9]
-----------------------------------------winow - add shift argument
[0, 1, 2]
[1, 2, 3]
[2, 3, 4]
[3, 4, 5]
[4, 5, 6]
[5, 6, 7]
[6, 7, 8]
[7, 8, 9]
[8, 9]
[9]
-----------------------------------------batch--1
[array([0, 1]), array([2])]
[array([1, 2]), array([3])]
[array([2, 3]), array([4])]
[array([3, 4]), array([5])]
[array([4, 5]), array([6])]
[array([5, 6]), array([7])]
[array([6, 7]), array([8])]
[array([7, 8]), array([9])]
[array([8, 9])]
[array([9])]
-----------------------------------------batch--2
[0 1 2]
[3 4 5]
[6 7 8]
[9]


In [3]:
# x = tf.convert_to_tensor(range(100))
window_size = 10
x = range(100)
# x = np.asarray(x).reshape(10, -1)
print(x)
print('----------------------')
x = tf.data.Dataset.from_tensor_slices(x) # Creates a Dataset whose elements are slices of the given tensors.
print(list(x.as_numpy_iterator()))
print()


x = x.window(window_size+1, shift=1, drop_remainder=True)

cnt = 0
print('print examples')
for k in x:
    print(list(k.as_numpy_iterator()))
    cnt += 1
    if cnt >= 10:
        break
        

range(0, 100)
----------------------
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]

print examples
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
[3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
[4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
[6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
[7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
[8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
[9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [4]:
x = x.flat_map(lambda w: w.batch(window_size+1))

'''
flat_map(
    map_func, name=None
)
Maps map_func across this dataset and flattens the result.
'''
print(list(x.as_numpy_iterator()))


[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13]), array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]), array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]), array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]), array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17]), array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18]), array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]), array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]), array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]), array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]), array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]), array([14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]), array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]), array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]), array([17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]), array([18, 19, 20, 21, 22, 23, 24, 25, 26, 27

In [5]:
x = x.map(lambda w: (w[:-1], w[-1]))
print(list(x.as_numpy_iterator()))

[(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 10), (array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), 11), (array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), 12), (array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), 13), (array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13]), 14), (array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14]), 15), (array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15]), 16), (array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16]), 17), (array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17]), 18), (array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]), 19), (array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]), 20), (array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]), 21), (array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21]), 22), (array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22]), 23), (array([14, 15, 16, 17, 18, 19, 20, 21, 22, 23]), 24), (array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24]), 25), (array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25]), 26), (array([17, 18, 19, 20, 21, 22, 23, 24, 25, 26]), 27), (array([18, 19, 20,

In [6]:
x = x.shuffle(buffer_size=10)
print(list(x.as_numpy_iterator())[:2])

[(array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15]), 16), (array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17]), 18)]


In [7]:
x = x.batch(5)
print('-' * 80, 'batch')
print(list(x.as_numpy_iterator())[:2])

-------------------------------------------------------------------------------- batch
[(array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16]]), array([11, 20, 14, 21, 17])), (array([[ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17]]), array([19, 24, 10, 22, 18]))]


In [8]:
x = x.prefetch(1)
print('-' * 80, 'prefetch')
print(list(x.as_numpy_iterator())[:2])

-------------------------------------------------------------------------------- prefetch
[(array([[ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]), array([17, 11, 10, 14, 21])), (array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23, 24, 25, 26, 27]]), array([12, 19, 22, 16, 28]))]


#### Put all to one function

In [9]:
def process_data(arr, window_size, batch_size):
    """
    arr is a numpy array
    
    """
    x = tf.data.Dataset.from_tensor_slices(arr)
    x = x.window(window_size+1, shift=1, drop_remainder=True)
    x = x.flat_map(lambda w: w.batch(window_size+1))
    x = x.map(lambda w: (w[:-1], w[-1]))
    x = x.shuffle(buffer_size=10)
    x = x.batch(batch_size).prefetch(2)
    return x

arr = range(100)
x = process_data(arr, 10, 3)

for i,j in x:
    print(i.numpy())
    print(j.numpy())

[[ 8  9 10 11 12 13 14 15 16 17]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 3  4  5  6  7  8  9 10 11 12]]
[18 17 13]
[[ 2  3  4  5  6  7  8  9 10 11]
 [13 14 15 16 17 18 19 20 21 22]
 [ 9 10 11 12 13 14 15 16 17 18]]
[12 23 19]
[[14 15 16 17 18 19 20 21 22 23]
 [10 11 12 13 14 15 16 17 18 19]
 [ 1  2  3  4  5  6  7  8  9 10]]
[24 20 11]
[[16 17 18 19 20 21 22 23 24 25]
 [19 20 21 22 23 24 25 26 27 28]
 [17 18 19 20 21 22 23 24 25 26]]
[26 29 27]
[[ 0  1  2  3  4  5  6  7  8  9]
 [15 16 17 18 19 20 21 22 23 24]
 [ 4  5  6  7  8  9 10 11 12 13]]
[10 25 14]
[[ 6  7  8  9 10 11 12 13 14 15]
 [20 21 22 23 24 25 26 27 28 29]
 [12 13 14 15 16 17 18 19 20 21]]
[16 30 22]
[[25 26 27 28 29 30 31 32 33 34]
 [26 27 28 29 30 31 32 33 34 35]
 [21 22 23 24 25 26 27 28 29 30]]
[35 36 31]
[[23 24 25 26 27 28 29 30 31 32]
 [24 25 26 27 28 29 30 31 32 33]
 [28 29 30 31 32 33 34 35 36 37]]
[33 34 38]
[[31 32 33 34 35 36 37 38 39 40]
 [11 12 13 14 15 16 17 18 19 20]
 [32 33 34 35 36 37 38 39 40 41]]
[41 21 42]
[

In [10]:
def windowed_dataset(series, window_size, batch_size, shuffle_buffer):
    # YOUR CODE HERE
    #series = tf.expand_dims(series, axis=-1)
    ds = tf.data.Dataset.from_tensor_slices(series)
    ds = ds.window(window_size + 1, shift=1, drop_remainder=True)
    ds = ds.flat_map(lambda w: w.batch(window_size + 1))
    ds = ds.shuffle(shuffle_buffer)
    ds = ds.map(lambda w: (w[:-1], w[-1]))
    return ds.batch(batch_size).prefetch(1)

arr = range(100)
x = windowed_dataset(arr, 10, 2, 10)

for i,j in x:
    print(i.numpy())
    print(j.numpy())
    break

[[ 2  3  4  5  6  7  8  9 10 11]
 [ 0  1  2  3  4  5  6  7  8  9]]
[12 10]
