In [2]:
from tensorflow.keras.preprocessing.sequence import TimeseriesGenerator
from tensorflow.keras import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense, LSTM, Lambda, Flatten, InputLayer
import tensorflow as tf

In [13]:
train = range(100)
# How many record to take into account
length = 10
batch_size = 3

# 1 beacause it's univariate
generator = TimeseriesGenerator(train, train, stride=1, length=length, batch_size=batch_size)

In [14]:
generator

In [15]:
for i,j in generator:
    print(i, '->', j)
    x = tf.expand_dims(i, axis=-1)
    print(x,)
    break
print(generator[0], generator[1], generator[2])

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 2  3  4  5  6  7  8  9 10 11]] -> [10 11 12]
tf.Tensor(
[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]]

 [[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]

 [[ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]
  [11]]], shape=(3, 10, 1), dtype=int32)
(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11]]), array([10, 11, 12])) (array([[ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]), array([13, 14, 15])) (array([[ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17]]), array([16, 17, 18]))


In [92]:
model = Sequential([InputLayer(input_shape=(length,)),
                    Lambda(lambda x: tf.expand_dims(x, axis=-1)),                    
                    LSTM(8,  input_shape=(length, )),
                    Flatten(),
                    Dense(1)])
model.compile(loss='mae', optimizer='adam', metrics=['mape'])
model.summary()

Model: "sequential_30"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lambda_8 (Lambda)            (None, 10, 1)             0         
_________________________________________________________________
lstm_29 (LSTM)               (None, 8)                 320       
_________________________________________________________________
flatten_6 (Flatten)          (None, 8)                 0         
_________________________________________________________________
dense_29 (Dense)             (None, 1)                 9         
Total params: 329
Trainable params: 329
Non-trainable params: 0
_________________________________________________________________


In [93]:
model.fit(generator, epochs=10)

Epoch 1/10
90/90 [==============================] - 1s 3ms/step - loss: 53.9054 - mape: 98.1597
Epoch 2/10
90/90 [==============================] - 0s 3ms/step - loss: 53.2896 - mape: 96.3347
Epoch 3/10
90/90 [==============================] - 0s 3ms/step - loss: 52.1973 - mape: 93.1916
Epoch 4/10
90/90 [==============================] - 0s 3ms/step - loss: 50.2100 - mape: 88.4784
Epoch 5/10
90/90 [==============================] - 0s 3ms/step - loss: 48.5717 - mape: 83.7879
Epoch 6/10
90/90 [==============================] - 0s 3ms/step - loss: 46.3901 - mape: 78.9452
Epoch 7/10
90/90 [==============================] - 0s 3ms/step - loss: 45.2610 - mape: 76.0039
Epoch 8/10
90/90 [==============================] - 0s 3ms/step - loss: 44.3133 - mape: 73.4414
Epoch 9/10
90/90 [==============================] - 0s 3ms/step - loss: 43.1756 - mape: 70.7235
Epoch 10/10
90/90 [==============================] - 0s 3ms/step - loss: 42.1563 - mape: 68.5156


In [97]:
import numpy as np
train = range(100)
# How many record to take into account
length = 10
batch_size = 1

train = np.expand_dims(np.array(train), axis=-1)
train[:10]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [105]:
# 1 beacause it's univariate
generator = TimeseriesGenerator(train, train, stride=1, length=length, batch_size=batch_size)
generator[0][0].shape # (batch_size, number_of_steps, features) = (1, 10, 1)

(1, 10, 1)

In [102]:
model = Sequential([InputLayer(input_shape=(length, 1)),
                    #Lambda(lambda x: tf.expand_dims(x, axis=-1)),                    
                    LSTM(8,  input_shape=(length, )),
                    Flatten(),
                    Dense(1)])
model.compile(loss='mae', optimizer='adam', metrics=['mape'])
model.summary()

Model: "sequential_33"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_32 (LSTM)               (None, 8)                 320       
_________________________________________________________________
flatten_9 (Flatten)          (None, 8)                 0         
_________________________________________________________________
dense_32 (Dense)             (None, 1)                 9         
Total params: 329
Trainable params: 329
Non-trainable params: 0
_________________________________________________________________


In [103]:
model.fit(generator, epochs=10)

Epoch 1/10
90/90 [==============================] - 2s 3ms/step - loss: 54.7885 - mape: 100.6274
Epoch 2/10
90/90 [==============================] - 0s 3ms/step - loss: 53.5366 - mape: 97.5498
Epoch 3/10
90/90 [==============================] - 0s 3ms/step - loss: 52.4501 - mape: 94.5615
Epoch 4/10
90/90 [==============================] - 0s 3ms/step - loss: 51.0509 - mape: 91.0557
Epoch 5/10
90/90 [==============================] - 0s 3ms/step - loss: 50.2010 - mape: 88.7372
Epoch 6/10
90/90 [==============================] - 0s 3ms/step - loss: 49.3650 - mape: 86.6638
Epoch 7/10
90/90 [==============================] - 0s 3ms/step - loss: 48.6483 - mape: 84.8250
Epoch 8/10
90/90 [==============================] - 0s 3ms/step - loss: 47.9534 - mape: 82.9457
Epoch 9/10
90/90 [==============================] - 0s 3ms/step - loss: 47.2683 - mape: 81.0963
Epoch 10/10
90/90 [==============================] - 0s 3ms/step - loss: 46.4347 - mape: 78.8692


In [2]:
from tensorflow.keras.preprocessing.sequence import TimeseriesGenerator
from tensorflow.keras import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense, LSTM, Lambda, Flatten, InputLayer
import tensorflow as tf


train = range(100)
# How many record to take into account
length = 10
batch_size = 1

labels = range(100, 200)

# 1 beacause it's univariate
generator = TimeseriesGenerator(train, labels, stride=1, length=length, batch_size=batch_size)

print(generator[0], generator[1])


(array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]), array([110])) (array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), array([111]))
