from tensorflow.keras.layers import Embedding

Embedding(input_dims, output_dims, input_length)

Embedding is to convert a matrix to higher dimension, each element in the original matrix will be converted to a <output_dims> size array.

assume your input is (batch_size, input_length), the output shape will be (batch_size, input_length,  output_dims)

input_dims is the np.nunique(), that is how many unique elements in this matrix.
output_dims is the embedding dimension.





In [7]:
from tensorflow.keras.layers import Embedding
import numpy as np

x = [1,2,4,1]

print(np.asarray(x).shape, 'input shape')
print(Embedding(input_dim=5, output_dim=4, input_length=None)(np.asarray(x)))
print(Embedding(input_dim=5, output_dim=4, input_length=4)(np.asarray(x)))
print(Embedding(input_dim=5, output_dim=4, input_length=3)(np.asarray(x)).shape)

print('###################')

x = [[1,2,4], [3,5,6]]

print(np.asarray(x).shape, 'input shape')

print(Embedding(input_dim=7, output_dim=4, input_length=None)(np.asarray(x)).shape)

print('###################')
x = [[[1,2,4], [3,5,6]], [[1,2,4], [3,5,6]]]
print(np.asarray(x).shape, 'input shape')

print(Embedding(input_dim=7, output_dim=4, input_length=3)(np.asarray(x)).shape)


(4,) input shape
tf.Tensor(
[[ 0.0298583   0.04626484  0.01171456  0.0496533 ]
 [ 0.02824173 -0.00289433 -0.02393568  0.01701376]
 [ 0.0037143  -0.02745137  0.01740715  0.0195791 ]
 [ 0.0298583   0.04626484  0.01171456  0.0496533 ]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[ 0.04209925 -0.04736764 -0.01638738 -0.03430145]
 [ 0.04235135  0.01985892  0.03813492  0.01290094]
 [-0.00801114  0.0300547   0.02101244  0.03156258]
 [ 0.04209925 -0.04736764 -0.01638738 -0.03430145]], shape=(4, 4), dtype=float32)
(4, 4)
###################
(2, 3) input shape
(2, 3, 4)
###################
(2, 2, 3) input shape
(2, 2, 3, 4)


In [12]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

train_data = [
  "I enjoy coffee.",
  "I enjoy tea.",
  "I dislike milk.",
  "I am going to the supermarket later this morning for some coffee."
]

test_data = [
  "Enjoy coffee this morning.",
  "I enjoy going to the supermarket.",
  "Want some milk for your coffee?"
]

In [8]:
num_words = 1000
oov_token = '<UNK>'
pad_type = 'post'
trunc_type = 'post'


In [9]:
# Tokenize our training data
tokenizer = Tokenizer(num_words=num_words, oov_token=oov_token)
tokenizer.fit_on_texts(train_data)


"""
num_words: the maximum number of words to keep, based on word frequency. 
Only the most common num_words-1 words will be kept.

filters: a string where each element is a character that will be filtered from the texts.
The default is all punctuation, plus tabs and line breaks, minus the ' character.

lower: boolean. Whether to convert the texts to lowercase.

split: str. Separator for word splitting.

char_level: if True, every character will be treated as a token.

oov_token: if given, it will be added to word_index and used to replace out-of-vocabulary words during text_to_sequence calls

analyzer: function. Custom analyzer to split the text. The default analyzer is text_to_word_sequence
"""


# Get our training data word index
word_index = tokenizer.word_index

print(word_index)

{'<UNK>': 1, 'i': 2, 'enjoy': 3, 'coffee': 4, 'tea': 5, 'dislike': 6, 'milk': 7, 'am': 8, 'going': 9, 'to': 10, 'the': 11, 'supermarket': 12, 'later': 13, 'this': 14, 'morning': 15, 'for': 16, 'some': 17}


In [10]:
# Encode training data sentences into sequences
train_sequences = tokenizer.texts_to_sequences(train_data)
train_sequences


[[2, 3, 4], [2, 3, 5], [2, 6, 7], [2, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 4]]

In [12]:
other_data = ["I enjoy coffee too.", "Wait a minute! Woodpecker"]
other_sequence = tokenizer.texts_to_sequences(other_data)
other_sequence


[[2, 3, 4, 1], [1, 1, 1, 1]]

In [5]:
# Get max training sequence length
maxlen = max([len(x) for x in train_sequences])

# Pad the training sequences
train_padded = pad_sequences(train_sequences, padding=pad_type, truncating=trunc_type, maxlen=maxlen)

# Output the results of our work
print("Word index:\n", word_index)
print("\nTraining sequences:\n", train_sequences)
print("\nPadded training sequences:\n", train_padded)
print("\nPadded training shape:", train_padded.shape)
print("Training sequences data type:", type(train_sequences))
print("Padded Training sequences data type:", type(train_padded))

Word index:
 {'<UNK>': 1, 'i': 2, 'enjoy': 3, 'coffee': 4, 'tea': 5, 'dislike': 6, 'milk': 7, 'am': 8, 'going': 9, 'to': 10, 'the': 11, 'supermarket': 12, 'later': 13, 'this': 14, 'morning': 15, 'for': 16, 'some': 17}

Training sequences:
 [[2, 3, 4], [2, 3, 5], [2, 6, 7], [2, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 4]]

Padded training sequences:
 [[ 2  3  4  0  0  0  0  0  0  0  0  0]
 [ 2  3  5  0  0  0  0  0  0  0  0  0]
 [ 2  6  7  0  0  0  0  0  0  0  0  0]
 [ 2  8  9 10 11 12 13 14 15 16 17  4]]

Padded training shape: (4, 12)
Training sequences data type: <class 'list'>
Padded Training sequences data type: <class 'numpy.ndarray'>


In [26]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.layers import Embedding

In [18]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Embedding(input_dim=1000, output_dim=64, input_length=10))
# The model will take as input an integer matrix of size (batch,
# input_length), and the largest integer (i.e. word index) in the input
# should be no larger than 999 (vocabulary size).
# Now model.output_shape is (None, 10, 64), where `None` is the batch
# dimension.
input_array = np.random.randint(1000, size=(32, 10))
model.compile('rmsprop', 'mse')
output_array = model.predict(input_array)
print(output_array.shape)


(32, 10, 64)


In [19]:
Embedding(input_dim=100, output_dim=10)

In [23]:
(train_padded)

array([[ 2,  3,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 2,  3,  5,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 2,  6,  7,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 2,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,  4]])

In [22]:
Embedding(input_dim=18, output_dim=3)(train_padded) # since the largeset number is 17, so, the input_dim is 18

<tf.Tensor: shape=(4, 12, 3), dtype=float32, numpy=
array([[[ 0.04241655, -0.04044966,  0.0050756 ],
        [ 0.03242183,  0.01625469, -0.03169619],
        [-0.01406216, -0.0284556 , -0.01600685],
        [-0.00468552, -0.04007109,  0.01506824],
        [-0.00468552, -0.04007109,  0.01506824],
        [-0.00468552, -0.04007109,  0.01506824],
        [-0.00468552, -0.04007109,  0.01506824],
        [-0.00468552, -0.04007109,  0.01506824],
        [-0.00468552, -0.04007109,  0.01506824],
        [-0.00468552, -0.04007109,  0.01506824],
        [-0.00468552, -0.04007109,  0.01506824],
        [-0.00468552, -0.04007109,  0.01506824]],

       [[ 0.04241655, -0.04044966,  0.0050756 ],
        [ 0.03242183,  0.01625469, -0.03169619],
        [-0.01698017,  0.01756532, -0.01632979],
        [-0.00468552, -0.04007109,  0.01506824],
        [-0.00468552, -0.04007109,  0.01506824],
        [-0.00468552, -0.04007109,  0.01506824],
        [-0.00468552, -0.04007109,  0.01506824],
        [-0.004

In [31]:
input_shape = (2, 3, 4)
x1 = tf.random.normal(input_shape)
x2 = np.random.randint(low=0, high=10, size=(2,3, 4))

print(x1, '\n\n', x2)

-------------
tf.Tensor(
[[[-0.01400142  0.43735096 -0.7691392  -0.9390922 ]
  [-0.6324583  -0.01914891 -0.89955014  0.33869278]
  [-1.9478154  -0.6656561  -0.19483899 -1.1875447 ]]

 [[-0.5147505   0.4984039   0.906299    0.08101185]
  [-1.0919018   0.7116297   0.91138214 -1.2478153 ]
  [ 1.5654184   0.01883395 -0.8530751   0.9618612 ]]], shape=(2, 3, 4), dtype=float32) 

 [[[5 5 1 5]
  [1 5 0 4]
  [2 8 8 7]]

 [[0 1 5 3]
  [2 7 5 7]
  [6 7 8 8]]]


In [34]:
x2

array([[[5, 5, 1, 5],
        [1, 5, 0, 4],
        [2, 8, 8, 7]],

       [[0, 1, 5, 3],
        [2, 7, 5, 7],
        [6, 7, 8, 8]]])

In [35]:
y = tf.keras.layers.GlobalAveragePooling1D()(x2)
print(y.shape)

print(x2, y)
print("-----------------------")

(2, 4)
[[[5 5 1 5]
  [1 5 0 4]
  [2 8 8 7]]

 [[0 1 5 3]
  [2 7 5 7]
  [6 7 8 8]]] tf.Tensor(
[[2 6 3 5]
 [2 5 6 6]], shape=(2, 4), dtype=int32)
-----------------------


In [36]:
x2.astype(float)

array([[[5., 5., 1., 5.],
        [1., 5., 0., 4.],
        [2., 8., 8., 7.]],

       [[0., 1., 5., 3.],
        [2., 7., 5., 7.],
        [6., 7., 8., 8.]]])

In [37]:
y = tf.keras.layers.GlobalAveragePooling1D()(x2.astype(float))
print(y.shape)

print(x2, y)
print("-----------------------")

(2, 4)
[[[5 5 1 5]
  [1 5 0 4]
  [2 8 8 7]]

 [[0 1 5 3]
  [2 7 5 7]
  [6 7 8 8]]] tf.Tensor(
[[2.6666667 6.        3.        5.3333335]
 [2.6666667 5.        6.        6.       ]], shape=(2, 4), dtype=float32)
-----------------------


In [46]:
y = tf.keras.layers.GlobalAveragePooling1D(data_format='channels_first')(x2.astype(float)) # the default is channels_last
print(y.shape)


print(x2, y)
print("-----------------------")
print(x2.shape) 
# If data_format='channels_last': 3D tensor with shape: (batch_size, steps, features)
# If data_format='channels_first': 3D tensor with shape: (batch_size, features, steps)


(2, 3)
[[[7 7 8 6]
  [5 8 2 3]
  [2 3 1 3]]

 [[5 3 5 0]
  [1 9 2 2]
  [5 4 9 2]]] tf.Tensor(
[[7.   4.5  2.25]
 [3.25 3.5  5.  ]], shape=(2, 3), dtype=float32)
-----------------------
(2, 3, 4)


In [2]:
from tensorflow.keras.layers import Embedding
import tensorflow as tf
x = [1,2,3,3,2,1]
Embedding(input_dim=4, output_dim=5)(tf.constant(x))


<tf.Tensor: shape=(6, 5), dtype=float32, numpy=
array([[-3.00862323e-02,  4.49339189e-02, -2.94989236e-02,
         3.85195017e-06, -3.42002288e-02],
       [-3.04150581e-03, -3.85608450e-02, -1.44257173e-02,
        -1.82052031e-02, -2.26071123e-02],
       [ 3.91150601e-02,  1.24029629e-02, -3.72429863e-02,
         1.45435445e-02, -1.28936656e-02],
       [ 3.91150601e-02,  1.24029629e-02, -3.72429863e-02,
         1.45435445e-02, -1.28936656e-02],
       [-3.04150581e-03, -3.85608450e-02, -1.44257173e-02,
        -1.82052031e-02, -2.26071123e-02],
       [-3.00862323e-02,  4.49339189e-02, -2.94989236e-02,
         3.85195017e-06, -3.42002288e-02]], dtype=float32)>

In [35]:
import numpy as np
import pandas as pd

x = list('abcda')
#x = tf.convert_to_tensor(x)

tokenizer = Tokenizer(num_words=6, oov_token='<OOV>')

tokenizer.fit_on_texts(x)

print(tokenizer.word_index)

y = list('abcdfg')
tokenizer.texts_to_sequences(y)

#Embedding(input_dim=4, output_dim=5)(x)


{'<OOV>': 1, 'a': 2, 'b': 3, 'c': 4, 'd': 5}


[[2], [3], [4], [5], [1], [1]]